version: "3"
volumes:
  pgdata:
services:
  postgres:
    image: postgres:13
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: db_development
    restart: always
    volumes:
        - pgdata:/var/lib/postgresql/data
    ports:
        - 5432:5432
